### ISSUE TITLE
Products not getting rendered

### ISSUE THREAD

**Issue by naszifnaaz** [kkalyankumar9/loud-weight-1875#20]
Products are not getting rendered, seems like there is no data in the JSON server. Fix it

**Comment by kkalyankumar9** [comment]
The product page rendering issue is resolved sir.

**Comment by kkalyankumar9** [comment]
The product page rendering issue resolved
 https://loud-weight-1875-5z2fm72g3-kummarikalyan010-gmailcom.vercel.app/
